### ISSUE TITLE
meta:최초 안내페이지 토론

### ISSUE THREAD

**Issue by baesy0** [RD101/dotori#1055]
### 애니메이션이 좋은가?
- [ ] 자동 애니메이션은 없애자
- [ ] 클릭으로 넘어가도록(페이지처럼)
### 최근의 기준
- [x] 개수를 기준으로 최근 n개
### 최근에 올라온 에셋 n건
- [x] n은 실제 아이템 갯수와 일치하면 좋겠다.
- [x] 올라온 -> 등록된
### 태그를 어떻게 할지.
- [x] 태그는 아이템 타입에 상관없이 연산
- 사이즈가 좀 더 컸으면 좋겠다. (보류 -> 채윤님당첨)

**Comment by khw7096** [comment]
이 이슈는 이제 닫아도 좋을 것 같다.
