### ISSUE TITLE
meta: 즐겨찾기가 있었으면 좋겠다.

### ISSUE THREAD

**Issue by 78963l** [RD101/dotori#1312]

**Comment by ChaeyunBae** [comment]
팀마다 자주 사용하는 어셋들이 생길 거라고 생각해서요. -  [ ] : User struct에 `FavoriteAssets` 자료구조를 추가한다.
- [ ] : 아이템 카드에 즐겨찾기 버튼 추가
- [ ] : 즐겨찾기 버튼 누르면 favorite assets에 item id 를 append 시키는 handler 추가
- [ ] : 즐겨찾기 모음 페이지 추가

이런 순서로

**Comment by khw7096** [comment]
좋아용.

**Comment by baesy0** [comment]
좋아용:)

**Comment by ChaeyunBae** [comment]
이거 제가 해보겠습니당

**Comment by khw7096** [comment]
즐겨찾기 옵션이 생겼으니 이 이슈를 닫는건 어때요?

**Comment by khw7096** [comment]
즐겨찾기 메뉴가 생성되었으니 이 이슈를 닫습니다.
