### ISSUE TITLE
도토리 실행시 자동으로 서비스 등록 될 수 있도록 하기

### ISSUE THREAD

**Issue by khw7096** [RD101/dotori#1472]
## 목적
정전시 서비스 자동 재시작

## Todo
- [x] 1차 문서화
- [x] Github Last release version 문서화
- [x] dotori 서버에 설치 및 실행
- [x] dotori 서버 적용
- [x] csi 서버 적용

#### Reference
- 간단한 방법: https://chhanz.github.io/linux/2019/01/18/linux-how-to-create-custom-systemd-service/
- 로그처리가 잘 나옴: https://khanakia.medium.com/golang-running-a-go-binary-as-a-systemd-service-on-ubuntu-18-04-in-10-minutes-without-docker-e5a1e933bb7e
- 한글 설명 추가: https://linsoo.pe.kr/archives/27933

**Comment by khw7096** [comment]
~/go/bin 경로가 좋을까?
위 경로는 개발할 때 사용하는 경로이니 공식 경로가 좋을 것 같다.

/usr/local/bin

**Comment by khw7096** [comment]
https://www.pathname.com/fhs/

경로 사용법
